apiVersion: mxl.media.fn/v1alpha1
kind: MxlMediaFunctionParameters
metadata:
  name: writer-1080p25-v210
  label:
    app: media-processing-3G
    function: video-writer
  namespace: media
spec:
  role: video-writer
  flow:
    label: "studio-cam-1"

  # Media input specifications
  inputs:
    - primary-feed:
      format:
        video:
          media_type: video/v210
          frame_width: 1920
          frame_height: 1080
          frame_rate: "25"

    - secondary-feed:
      format:
        video:
          media_type: video/v210
          frame_width: 1920
          frame_height: 1080
          frame_rate: "25"
  # Media output specifications
  outputs:
    processed-output:
      format:
        video:
          media_type: video/v210
          frame_width: 1920
          frame_height: 1080
          frame_rate: "25"

  args:  # All arguments that are relevant for the media function, and can be used for resources utilization should be included here.
    - resolution: "1080p"
    - frame_rate: "25fps"
    - format: "v210"

  # Resource requirements for the media function
  requirements:
    cpu:
      cpu: "2000m"              # Millicores (m): A fractional part of a core. 1 CPU is equal to 1000m. 500m: Half a core (0.5 CPU).100m: One-tenth of a core (0.1 CPU
      features:
        - null

    memory:
      - type: ram
        size: "4Gi"             # Requests and limits in units as expressed in Kubernetes (e.g., Mi, Gi)
        throughput:
          read: "2000MBi"
          write: "4000MBi"
          total: "6Gi"          # Total memory bandwidth required (if applicable)

    network:
      # v210 @ 1920x1080p25
      # bytes_per_frame = (ceil(1920 / 48) * 128) * 1080 = 5,529,600 bytes
      # media_bytes_per_second = 5,529,600 * 25 = 138,240,000 B/s
      # packets_per_second = ceil(bytes_per_frame / (mtu - 44)) * frame_rate
      # wire_bytes_per_second = media_bytes_per_second + packets_per_second * 82
      # Using mtu = 1400 => wire_bytes_per_second = 146,599,900 B/s
      inputs:
        primary-feed:
          transport:
            selected: "RDMA"       # Possible alternatives: EFA, TCP
          bandwidth: "0.14660GB/S" # One v210 input stream on wire (with overhead)
        secondary-feed:
          transport:
            selected: "RDMA"       # Possible alternatives: EFA, TCP
          bandwidth: "0.14660GB/S" # One v210 input stream on wire (with overhead)
      outputs:
        processed-output:
          transport:
            selected: "RDMA"       # Possible alternatives: EFA, TCP
          bandwidth: "0.14660GB/S" # One processed v210 output stream on wire (with overhead)


  # host platform capabilities
    host_capabilities:
      cpu:
        numa_nodes: 2
        number_of_cores: 16
        base_frequency: "2.8GHz"
        generation: "Emerald Rapids"  # CPU microarchitecture generation (e.g., Skylake, Ice Lake, etc.)
        # Selected CPU features discovered via NFD or cpuid
        features:
          - AVX512F
          - AVX512DQ
          - SGX

      network:
        - name: eth0
          bandwidth:
            input: 12.5GB/S
            output: 12.5GB/S
          features:
            - jumbo_frames
            - rdma

      gpu:
        - name: gpu_0
          generation: Ampere
          memory: 16Gi
          compute_units: 1000m # some arbitrary unit of compute capability
          capabilities: # driver-specific GPU features (e.g., CUDA compute capability, or a custom set of flags)
            - tensor_operations
            - high_precision_compute

      memory:
        - node: 0
          type: ram
          generation: DDR5
          size: 128Gi
          throughput:
            total: 125Gi
        - node: 1
          type: ram
          generation: DDR5
          size: 128Gi
          throughput:
            total: 125Gi

      storage:
        - name: nvme_0
          type: nvme # or nvme, ssd, hdd, spinning_disk, etc.
          throughput:
            read: 2000M
            write: 1800M
